name: Update locales

permissions:
  contents: write

on:
  schedule:
    - cron: 0 */2 * * *
  workflow_dispatch:
    inputs:
      export_languages:
        description: Comma-separated languages to export (en-US), blank for all
        type: string
        required: false

jobs:
  minecraft:
    name: Minecraft
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Set up Python and uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.11

      - name: Install dependencies
        env:
          DOTNET_CLI_WORKLOAD_UPDATE_NOTIFY_DISABLE: true
        run: |
          uv sync
          cd tools/XvdTool.Streaming
          dotnet publish XvdTool.Streaming/XvdTool.Streaming.csproj -c Release -o ./x64 -r win-x64 --no-self-contained -nowarn:ca1416,ca2022,cs0168

      - name: Update language files
        env:
          CIK_DATA: ${{ secrets.CIK_DATA }}
          EXPORT_LANGUAGES: ${{ inputs.export_languages }}
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          uv run scripts/java/update.py
          $JAVA_CHANGED = [Environment]::GetEnvironmentVariable('JAVA_CHANGED', 'User')
          $JAVA_EDITION = [Environment]::GetEnvironmentVariable('JAVA_EDITION', 'User')
          if ($JAVA_CHANGED) {
            git add .
            git commit -m "Update Minecraft: Java Edition $JAVA_EDITION locales"
          } else {
            git checkout -- versions.json
          }
          $JAVA_COMMIT = git log --grep '^Update Minecraft: Java Edition .* locales$' -1 --format=%H
          uv run scripts/bedrock/extract.py
          $BEDROCK_CHANGED = [Environment]::GetEnvironmentVariable('BEDROCK_CHANGED', 'User')
          $BEDROCK_EDITION = [Environment]::GetEnvironmentVariable('BEDROCK_EDITION', 'User')
          if ($BEDROCK_CHANGED) {
            uv run scripts/bedrock/merge.py
            uv run scripts/bedrock/provider.py
            git add .
            git commit -m "Update Minecraft: Bedrock Edition $BEDROCK_EDITION locales"
          } else {
            git checkout -- versions.json
          }
          $BEDROCK_COMMIT = git log --grep '^Update Minecraft: Bedrock Edition .* locales$' -1 --format=%H
          git push
          git submodule deinit tools/XvdTool.Streaming
          git clean -fdx
          git fetch origin history:history
          git switch --force history
          $data = Get-Content -path data.json
          $readme = Get-Content -path README.md
          if (-not ($readme | Select-String -pattern "<!--JE-->$JAVA_EDITION \|" -quiet)) {
            $data = $data.replace('"java": {', """java"": {`r`n    ""$JAVA_EDITION"": ""$JAVA_COMMIT"",")
            $readme = $readme.replace('| <!--JE-->', "| <!--JE-->$JAVA_EDITION | [``$JAVA_COMMIT``](https://github.com/teaSummer/minecraft-locales/tree/$JAVA_COMMIT) |`r`n| ")
          }
          if (-not ($readme | Select-String -pattern "<!--BE-->$BEDROCK_EDITION \|" -quiet)) {
            $data = $data.replace('"bedrock": {', """bedrock"": {`r`n    ""$BEDROCK_EDITION"": ""$BEDROCK_COMMIT"",")
            $readme = $readme.replace('| <!--BE-->', "| <!--BE-->$BEDROCK_EDITION | [``$BEDROCK_COMMIT``](https://github.com/teaSummer/minecraft-locales/tree/$BEDROCK_COMMIT) |`r`n| ")
          }
          Set-Content -path data.json -value $data
          Set-Content -path README.md -value $readme
          git add .
          git commit -m 'Record history'
          git push --set-upstream origin history
